### ISSUE TITLE
运行一周左右后，会出现服务访问不了的情况

### ISSUE THREAD

**Issue by LasseChi** [mingdaocom/private-deployment#27]
服务器配置：4c 16G centos 7
每次新启动一周左右的时间，就会出现服务访问不了的情况，自安装以来，每周都会出现这种情况。
查看服务器日志，发现报如下BUG：
![image](https://user-images.githubusercontent.com/29368935/112781519-94ff4080-907d-11eb-8981-2cc279fb169c.png)

**Comment by beckjin** [comment]
启动完成后执行以下命令看看健康检查是否正常：
```
docker logs `docker ps | grep mingdaoyun-community | awk '{print $1}'`
```

文档：https://docs.pd.mingdao.com/deployment/docker-compose/command.html

**Comment by LasseChi** [comment]
能启动成功，刚启动的时候所有服务都是正常的，但是正常运行了一周左右的时间就会出现无法访问的情况，然后服务器日志里面就记录了这个BUG

**Comment by beckjin** [comment]
无法访问的时候到服务器上看下各项资源的使用情况，另外执行上面发的目录再看下。如果方便保留现场，可以联系我们远程看看。

**Comment by LasseChi** [comment]
好的，谢谢

**Comment by LasseChi** [comment]
清明假期回来，发现大部分服务无法访问，于上周二重启，一切服务正常。今天发现工作流模块的服务没法访问，我运行
``` 
docker logs `docker ps | grep mingdaoyun-community | awk '{print $1}'`
``` 
就出现以下信息（只截取了部分信息，其他信息于这部分一样，好像是这两个服务不断的重启）：
```
Housekeeper | 2021-04-12 14:22:49 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:22:52 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:23:19 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:23:22 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:23:49 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:23:52 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:24:19 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:24:22 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:24:49 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:24:52 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:25:19 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:25:22 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:25:49 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:25:52 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-12 14:26:19 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-12 14:26:22 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
```
我推测会不会是因为某些服务停止服务后不断重启，最后导致负载过高，然后影响到了其他服务。

**Comment by LasseChi** [comment]
我通过日期筛选，发现这种情况是在4月10号晚上23:20:16开始的，好像全部服务都重启了一遍，然后workerflow和elasticsearch就不断的重启，信息如下（这段信息后面未截取的日志信息都是workflow和elasticsearch两个服务不断重启的信息）：
```
Housekeeper | 2021-04-10 23:20:16 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:20:46 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:21:13 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:21:43 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:22:32 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:22:32 |   ERROR |               Housekeeper | get alert: redis: nil 
Housekeeper | 2021-04-10 23:22:32 |    INFO |                     alert | /usr/bin/bash -c source /entrypoint.sh && alertShutdown 
Housekeeper | 2021-04-10 23:22:32 |   ERROR |               Housekeeper | get taskcenter-daily: redis: nil 
Housekeeper | 2021-04-10 23:22:32 |    INFO |          taskcenter-daily | /usr/bin/bash -c source /entrypoint.sh && taskcenter-dailyShutdown 
Housekeeper | 2021-04-10 23:22:32 |   ERROR |               Housekeeper | get calendaralert: redis: nil 
Housekeeper | 2021-04-10 23:22:33 |    INFO |             calendaralert | /usr/bin/bash -c source /entrypoint.sh && calendaralertShutdown 
Housekeeper | 2021-04-10 23:22:43 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:22:43 |    INFO |                     alert | /usr/bin/bash -c source /entrypoint.sh && alertStartup 
Housekeeper | 2021-04-10 23:22:44 |    INFO |          taskcenter-daily | /usr/bin/bash -c source /entrypoint.sh && taskcenter-dailyStartup 
Housekeeper | 2021-04-10 23:22:44 |    INFO |             calendaralert | /usr/bin/bash -c source /entrypoint.sh && calendaralertStartup 
Housekeeper | 2021-04-10 23:24:15 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:24:16 | WARNING |                 postcache | restart postcache: (1: [/usr/bin/bash -c source /entrypoint.sh && postcacheShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && postcacheStartup];) 
Housekeeper | 2021-04-10 23:24:18 | WARNING |                      file | restart file: (1: [/usr/bin/bash -c source /entrypoint.sh && fileShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && fileStartup];) 
Housekeeper | 2021-04-10 23:24:41 | WARNING |              notification | restart notification: (1: [/usr/bin/bash -c source /entrypoint.sh && notificationShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && notificationStartup];) 
Housekeeper | 2021-04-10 23:24:42 | WARNING |                       sms | restart sms: (1: [/usr/bin/bash -c source /entrypoint.sh && smsShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && smsStartup];) 
Housekeeper | 2021-04-10 23:25:15 | WARNING |                 searchapi | restart searchapi: (1: [/usr/bin/bash -c source /entrypoint.sh && searchapiShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && searchapiStartup];) 
Housekeeper | 2021-04-10 23:25:16 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-10 23:25:24 | WARNING |                      chat | restart chat: (1: [/usr/bin/bash -c source /entrypoint.sh && chatShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && chatStartup];) 
Housekeeper | 2021-04-10 23:25:36 | WARNING |                      push | restart push: (1: [/usr/bin/bash -c source /entrypoint.sh && pushShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && pushStartup];) 
Housekeeper | 2021-04-10 23:25:38 | WARNING |       generalintegrateapi | restart generalintegrateapi: (1: [/usr/bin/bash -c source /entrypoint.sh && generalintegrateapiShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && generalintegrateapiStartup];) 
Housekeeper | 2021-04-10 23:25:39 |   ERROR |               Housekeeper | get alert: redis: nil 
Housekeeper | 2021-04-10 23:25:40 |    INFO |                     alert | /usr/bin/bash -c source /entrypoint.sh && alertShutdown 
Housekeeper | 2021-04-10 23:25:40 |   ERROR |               Housekeeper | get taskcenter-daily: redis: nil 
Housekeeper | 2021-04-10 23:25:40 |    INFO |          taskcenter-daily | /usr/bin/bash -c source /entrypoint.sh && taskcenter-dailyShutdown 
Housekeeper | 2021-04-10 23:25:40 |   ERROR |               Housekeeper | get calendaralert: redis: nil 
Housekeeper | 2021-04-10 23:25:41 |    INFO |             calendaralert | /usr/bin/bash -c source /entrypoint.sh && calendaralertShutdown 
Housekeeper | 2021-04-10 23:25:49 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:25:51 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-10 23:26:11 | WARNING |                      chat | restart chat: (1: [/usr/bin/bash -c source /entrypoint.sh && chatShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && chatStartup];) 
Housekeeper | 2021-04-10 23:26:15 | WARNING |                      push | restart push: (1: [/usr/bin/bash -c source /entrypoint.sh && pushShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && pushStartup];) 
Housekeeper | 2021-04-10 23:26:16 | WARNING |       generalintegrateapi | restart generalintegrateapi: (1: [/usr/bin/bash -c source /entrypoint.sh && generalintegrateapiShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && generalintegrateapiStartup];) 
Housekeeper | 2021-04-10 23:26:16 |    INFO |                     alert | /usr/bin/bash -c source /entrypoint.sh && alertStartup 
Housekeeper | 2021-04-10 23:26:17 |    INFO |          taskcenter-daily | /usr/bin/bash -c source /entrypoint.sh && taskcenter-dailyStartup 
Housekeeper | 2021-04-10 23:26:17 |    INFO |             calendaralert | /usr/bin/bash -c source /entrypoint.sh && calendaralertStartup 
Housekeeper | 2021-04-10 23:26:20 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:26:21 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-10 23:26:42 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
Housekeeper | 2021-04-10 23:26:43 | WARNING |                  workflow | restart workflow: (1: [/usr/bin/bash -c source /entrypoint.sh && workflowShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && workflowStartup];) 
Housekeeper | 2021-04-10 23:27:12 | WARNING |             elasticsearch | restart elasticsearch: (1: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchShutdown]; 2: [/usr/bin/bash -c source /entrypoint.sh && elasticsearchStartup];) 
```

**Comment by LasseChi** [comment]
进入mingdaoyun-community实例，查看/data/logs/workflow.log 出现大量以下错误信息：
```
20:26:25.200 1018151575 [pool-1-thread-6] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:54)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:52)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:180)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.set(DefaultedRedisConnection.java:294)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.set(DefaultStringRedisConnection.java:982)
        at jdk.internal.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
        at com.sun.proxy.$Proxy220.set(Unknown Source)
        at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider$ShedlockRedisTemplate.lambda$tryToSetExpiration$0(RedisLockProvider.java:122)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
        at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider$ShedlockRedisTemplate.tryToSetExpiration(RedisLockProvider.java:122)
        at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider$ShedlockRedisTemplate.access$100(RedisLockProvider.java:116)
        at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider.lock(RedisLockProvider.java:67)
        at jdk.internal.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
        at com.sun.proxy.$Proxy82.lock(Unknown Source)
        at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:51)
        at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:40)
        at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
        at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.lettuce.core.RedisCommandExecutionException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
        at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135)
        at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:108)
        at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118)
        at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:680)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:640)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted
```

**Comment by beckjin** [comment]
@wb4646684

**Comment by wb4646684** [comment]
@LasseChi 这个情况多半是和服务器内存不足有关，建议安装一下sysstat工具进行主机监控数据收集。在出问题的时间查看主机监控是否有资源异常

**Comment by LasseChi** [comment]
我们目前有十个人左右在用，多少内存能合适

**Comment by beckjin** [comment]
和使用人数没有直接关系，主要和涉及的业务有关，如：工作表数据行数、工作流执行频率等等。

**Comment by LasseChi** [comment]
所有工作表总行数不到8000行，每天增长不到30行，工作流的触发都是工作表新增和更新记录事件触发，执行评率应该也不高，工作流的流程都是很简单的两三个步骤就结束的

**Comment by beckjin** [comment]
16G 一般足够了。你可以看下明道云服务的健康检查日志  docker logs `docker ps | grep mingdaoyun-community | awk '{print $1}'`

**Comment by LasseChi** [comment]
这个是当前内存占用情况（所有服务运行正常）：
![image](https://user-images.githubusercontent.com/29368935/116218938-9fe0ea00-a77d-11eb-8c40-83430e6df79b.png)

您说的这个命令我们也查过了，通过这个命令查到，所有服务自动重启的情况都是出现在周六，重启后，部分服务(每次失败的服务不同)重启失败，然后就是间隔30秒不断的重启。

**Comment by beckjin** [comment]
那周六是否有设置什么定时任务。

**Comment by beckjin** [comment]
先关闭了，有问题再沟通。
